language: java
sudo: false
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install: cd parent
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml &&  mvn deploy"
  skip_cleanup: true
  on:
    tags: true
