language: java
sudo: false
script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -f parent/pom.xml deploy"
dist: trusty
jdk: oraclejdk9
addons:  
  apt:    
     packages:      
       - oracle-java9-installer